USE DATABASE UDACITY;
USE SCHEMA DWH;

-- create FACT_REVIEW table
CREATE OR REPLACE TABLE FACT_REVIEW(
    "REVIEW_ID" VARCHAR(50),
    "USER_ID" VARCHAR(50),
    "BUSINESS_ID" VARCHAR(50),
    "STARS" FLOAT,
    "USEFUL" INTEGER,
    "FUNNY" INTEGER,
    "COOL" INTEGER,
    "TEXT" STRING,
    "DATE" DATE
);

-- create DIM_BUSINESS table
CREATE OR REPLACE TABLE DIM_BUSINESS(
  "BUSINESS_ID" VARCHAR(50),
  "NAME" VARCHAR(255),
  "ADDRESS" VARCHAR(255),
  "CITY" VARCHAR(255),
  "STATE" VARCHAR(10),
  "POSTAL_CODE" VARCHAR(10),
  "LATITUDE" FLOAT,
  "LONGITUDE" FLOAT,
  "STARS" FLOAT,
  "REVIEW_COUNT" INTEGER,
  "IS_OPEN" INTEGER,
  "ATTRIBUTES" VARIANT,
  "CATEGORIES" STRING,
  "HOURS" VARIANT,
  "HIGHLIGHTS" VARIANT,
  "DELIVERY_OR_TAKEOUT" VARIANT,
  "GRUBHUB_ENABLED" VARIANT,
  "CALL_TO_ACTION_ENABLED" VARIANT,
  "REQUEST_A_QUOTE_ENABLED" VARIANT,
  "COVID_BANNER" VARIANT,
  "TEMPORARY_CLOSED_UNTIL" VARIANT,
  "VIRTUAL_SERVICES_OFFERED" VARIANT,
  "CHECKIN_DATE" VARIANT
);

-- create DIM_USER table
CREATE OR REPLACE TABLE DIM_USER(
    "USER_ID" VARCHAR(50),
    "NAME" VARCHAR(255),
    "REVIEW_COUNT" INTEGER,
    "YELPING_SINCE" DATE,
    "USEFUL" INTEGER,
    "FUNNY" INTEGER,
    "COOL" INTEGER,
    "ELITE" STRING,
    "FRIENDS" VARIANT,
    "FANS" INTEGER,
    "AVERAGE_STARS" FLOAT,
    "COMPLIMENT_HOT" INTEGER,
    "COMPLIMENT_MORE" INTEGER,
    "COMPLIMENT_PROFILE" INTEGER,
    "COMPLIMENT_CUTE" INTEGER,
    "COMPLIMENT_LIST" INTEGER,
    "COMPLIMENT_NOTE" INTEGER,
    "COMPLIMENT_PLAIN" INTEGER,
    "COMPLIMENT_COOL" INTEGER,
    "COMPLIMENT_FUNNY" INTEGER,
    "COMPLIMENT_WRITER" INTEGER,
    "COMPLIMENT_PHOTOS" INTEGER
);

-- create DIM_CLIMATE table
CREATE OR REPLACE TABLE DIM_CLIMATE(
    "DATE" DATE,
    "MIN" FLOAT,
    "MAX" FLOAT,
    "NORMAL_MIN" FLOAT,
    "NORMAL_MAX" FLOAT,
    "PRECIPITATION" FLOAT,
    "PRECIPITATION_NORMAL" FLOAT
);


-------- INSERT INTO DWH FROM FROM ODS--------------------
-- Clone FACT_REVIEW, DIM_USER  from ODS_YELP_REVIEW, DIM_USER due to they are the same
CREATE OR REPLACE TABLE FACT_REVIEW clone ODS.ODS_YELP_REVIEW;
CREATE OR REPLACE TABLE DIM_USER clone ODS.ODS_YELP_USER;

-- DIM_BUSINESS
INSERT INTO DIM_BUSINESS(
  "BUSINESS_ID",
  "NAME",
  "ADDRESS",
  "CITY",
  "STATE",
  "POSTAL_CODE",
  "LATITUDE",
  "LONGITUDE",
  "STARS",
  "REVIEW_COUNT",
  "IS_OPEN",
  "ATTRIBUTES",
  "CATEGORIES",
  "HOURS",
  "HIGHLIGHTS",
  "DELIVERY_OR_TAKEOUT",
  "GRUBHUB_ENABLED",
  "CALL_TO_ACTION_ENABLED",
  "REQUEST_A_QUOTE_ENABLED",
  "COVID_BANNER",
  "TEMPORARY_CLOSED_UNTIL",
  "VIRTUAL_SERVICES_OFFERED",
  "CHECKIN_DATE"
)
SELECT bus.*,
       cov.HIGHLIGHTS,
       cov.DELIVERY_OR_TAKEOUT,
       cov.GRUBHUB_ENABLED,
       cov.CALL_TO_ACTION_ENABLED,
       cov.REQUEST_A_QUOTE_ENABLED,
       cov.COVID_BANNER,
       cov.TEMPORARY_CLOSED_UNTIL,
       cov.VIRTUAL_SERVICES_OFFERED,
       chk.DATE
FROM ODS.ODS_YELP_BUSINESS bus
    LEFT JOIN ODS.ODS_YELP_COVID cov ON bus.BUSINESS_ID = cov.BUSINESS_ID
    LEFT JOIN ODS.ODS_YELP_CHECKIN chk ON bus.BUSINESS_ID = chk.BUSINESS_ID;

-- DIM_CLIMATE
INSERT INTO DIM_CLIMATE(
    "DATE",
    "MIN",
    "MAX",
    "NORMAL_MIN",
    "NORMAL_MAX",
    "PRECIPITATION",
    "PRECIPITATION_NORMAL"
)
SELECT tem.*,
       pre.PRECIPITATION,
       pre.PRECIPITATION_NORMAL
FROM ODS.ODS_TEMPERATURE tem
    LEFT JOIN ODS.ODS_PRECIPITATION pre ON tem.DATE = pre.DATE;
