DROP TABLE IF EXISTS EDUCATIONS CASCADE;

DROP TABLE IF EXISTS STATES CASCADE;

DROP TABLE IF EXISTS CITIES CASCADE;

DROP TABLE IF EXISTS LOCATIONS CASCADE;

DROP TABLE IF EXISTS JOBS CASCADE;

DROP TABLE IF EXISTS DEPARTMENTS CASCADE;

DROP TABLE IF EXISTS EMPLOYEES CASCADE;

DROP TABLE IF EXISTS JOB_HISTORY CASCADE;