\echo Dropping table EDUCATIONS
DROP TABLE IF EXISTS EDUCATIONS CASCADE;

\echo Dropping table STATES
DROP TABLE IF EXISTS STATES CASCADE;

\echo Dropping table CITIES
DROP TABLE IF EXISTS CITIES CASCADE;

\echo Dropping table LOCATIONS
DROP TABLE IF EXISTS LOCATIONS CASCADE;

\echo Dropping table JOBS
DROP TABLE IF EXISTS JOBS CASCADE;

\echo Dropping table DEPARTMENTS
DROP TABLE IF EXISTS DEPARTMENTS CASCADE;

\echo Dropping table EMPLOYEES
DROP TABLE IF EXISTS EMPLOYEES CASCADE;

\echo Dropping table EMP_ASSIGNMENTS
DROP TABLE IF EXISTS EMP_ASSIGNMENTS CASCADE;